setup CI with docker hub.
conduktor/kafka-security-manager pull request #95
Opened 2021-03-04 20:31 UTC by Diablo2050

This has two CI files one for pull requests with tests only and the other has version tags and master push.

2021-03-04 21:06 UTC, simplesteph requested changes
I also think there's a problem: it doesn't run the test suit on pushes to master, right? Any push to master also needs to be tested to ensure we don't push a bad build out there

2021-03-04 21:06 UTC, simplesteph commented on docker_push.sh
> +    elif [[ "$RELEASE_VERSION" == "dev" ]]; then
@Diablo2050 what's that line for?

2021-03-04 21:06 UTC, simplesteph commented on docker_push.sh
> +    # elif [[ "$RELEASE_VERSION" == v* ]]; then
if comments, please remove?

2021-03-04 22:06 UTC, Diablo2050 commented on docker_push.sh
> +    elif [[ "$RELEASE_VERSION" == "dev" ]]; then
will be removed, should be == "master"

2021-03-04 22:06 UTC, Diablo2050 commented on docker_push.sh
> +    # elif [[ "$RELEASE_VERSION" == v* ]]; then
will be removed.

2021-03-05 12:55 UTC, Diablo2050 commented
@simplesteph changes done and test passed.

2021-03-05 19:31 UTC, merged